#ifndef CIELUTILS_INCLUDE_CIEL_ALGORITHM_HPP_
#define CIELUTILS_INCLUDE_CIEL_ALGORITHM_HPP_

#include <ciel/algorithm_impl/binary_search.hpp>
#include <ciel/algorithm_impl/clamp.hpp>
#include <ciel/algorithm_impl/copy.hpp>
#include <ciel/algorithm_impl/copy_backward.hpp>
#include <ciel/algorithm_impl/copy_if.hpp>
#include <ciel/algorithm_impl/copy_n.hpp>
#include <ciel/algorithm_impl/count.hpp>
#include <ciel/algorithm_impl/count_if.hpp>
#include <ciel/algorithm_impl/equal.hpp>
#include <ciel/algorithm_impl/equal_range.hpp>
#include <ciel/algorithm_impl/fill.hpp>
#include <ciel/algorithm_impl/fill_n.hpp>
#include <ciel/algorithm_impl/find.hpp>
#include <ciel/algorithm_impl/find_if.hpp>
#include <ciel/algorithm_impl/find_if_not.hpp>
#include <ciel/algorithm_impl/generate.hpp>
#include <ciel/algorithm_impl/generate_n.hpp>
#include <ciel/algorithm_impl/is_heap.hpp>
#include <ciel/algorithm_impl/is_heap_until.hpp>
#include <ciel/algorithm_impl/is_sorted.hpp>
#include <ciel/algorithm_impl/is_sorted_until.hpp>
#include <ciel/algorithm_impl/iter_swap.hpp>
#include <ciel/algorithm_impl/lexicographical_compare.hpp>
#include <ciel/algorithm_impl/lower_bound.hpp>
#include <ciel/algorithm_impl/make_heap.hpp>
#include <ciel/algorithm_impl/max.hpp>
#include <ciel/algorithm_impl/max_element.hpp>
#include <ciel/algorithm_impl/merge.hpp>
#include <ciel/algorithm_impl/min.hpp>
#include <ciel/algorithm_impl/min_element.hpp>
#include <ciel/algorithm_impl/minmax.hpp>
#include <ciel/algorithm_impl/minmax_element.hpp>
#include <ciel/algorithm_impl/mismatch.hpp>
#include <ciel/algorithm_impl/move.hpp>
#include <ciel/algorithm_impl/move_backward.hpp>
#include <ciel/algorithm_impl/next_permutation.hpp>
#include <ciel/algorithm_impl/partial_sort.hpp>
#include <ciel/algorithm_impl/pop_heap.hpp>
#include <ciel/algorithm_impl/prev_permutation.hpp>
#include <ciel/algorithm_impl/push_heap.hpp>
#include <ciel/algorithm_impl/remove.hpp>
#include <ciel/algorithm_impl/remove_if.hpp>
#include <ciel/algorithm_impl/reverse.hpp>
#include <ciel/algorithm_impl/rotate.hpp>
#include <ciel/algorithm_impl/sort.hpp>
#include <ciel/algorithm_impl/sort_heap.hpp>
#include <ciel/algorithm_impl/stable_sort.hpp>
#include <ciel/algorithm_impl/swap_ranges.hpp>
#include <ciel/algorithm_impl/transform.hpp>
#include <ciel/algorithm_impl/upper_bound.hpp>
#include <ciel/numeric.hpp>

#endif // CIELUTILS_INCLUDE_CIEL_ALGORITHM_HPP_