#ifndef CIELUTILS_INCLUDE_CIEL_STRING_H_
#define CIELUTILS_INCLUDE_CIEL_STRING_H_

#include <ciel/config.hpp>
#include <string>

NAMESPACE_CIEL_BEGIN

NAMESPACE_CIEL_END

#endif // CIELUTILS_INCLUDE_CIEL_STRING_H_