#ifndef CIELUTILS_INCLUDE_CIEL_TYPE_TRAITS_IMPL_VOID_T_HPP_
#define CIELUTILS_INCLUDE_CIEL_TYPE_TRAITS_IMPL_VOID_T_HPP_

#include <ciel/config.hpp>

NAMESPACE_CIEL_BEGIN

template<class...>
using void_t = void;

NAMESPACE_CIEL_END

#endif // CIELUTILS_INCLUDE_CIEL_TYPE_TRAITS_IMPL_VOID_T_HPP_